name: ci

on:
  pull_request:
  push: {branches: [main]}
  merge_group:

permissions:
  contents: read
  id-token: write

jobs:
  docs:
    uses: American-Tractor-Company/.github/.github/workflows/wf-docs.yml@v1
    with: {check-evidence: false}
  security:
    uses: American-Tractor-Company/.github/.github/workflows/wf-security.yml@v1
    with: {languages: '["javascript"]'}
  program:
    uses: American-Tractor-Company/.github/.github/workflows/wf-task-id.yml@v1
